[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "manim-derivative-plotter"
version = "1.0.5"
authors = [
  { name="TyrannoJ", email="julius.megerle@outlook.de" },
]
description = "a simple tool for plotting polynomial derivatives with manim"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "manim",
    "sympy",
    "typst"
]
license="MIT"
license-files = ["LICEN[CS]E*"]

[project.scripts]
render-animation="manim_derivatives.__init__:render_animation"
render-picture="manim_derivatives.__init__:render_picture"

[project.optional-dependencies]
typst = [
    "manim[typst]"
]

[project.urls]
Homepage = "https://github.com/TyrannoJ/manim"